#define _GLIBCXX_USE_C99 1
#include "../vm.h"
#include "manual.h"

extern std::vector<ManualKeyword> keywords;

void create_manual_string()
{
    keywords.push_back(ManualKeyword(
        "ASC",
        "ASC",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "CHR$",
        "CHR$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "INSTR",
        "INSTR",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "LEFT$",
        "LEFT$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "LEN",
        "LEN",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "MID$",
        "MID$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "PRINT",
        "PRINT",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "RIGHT$",
        "RIGHT$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "SPC",
        "SPC",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "STR$",
        "STR$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "STRING$",
        "STRING$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "TIME$",
        "TIME$",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
    keywords.push_back(ManualKeyword(
        "VAL",
        "VAL",
        KeywordCategory::STRING,
        "",
        {},
        "",
        "",
        ""));
}