20 LET X=RND(6)-1
30 PRINT "THE COMPUTER HAS CHOSEN A NUMBER BETWEEN 0 AND 5. CAN YOU GUESS IT?"
40 INPUT G
60 IF G=X THEN PRINT "WELL DONE!" ELSE PRINT "TOUGH LUCK - YOU'RE WRONG"
90 PRINT "DO YOU WANT ANOTHER GO? IF SO, PLEASE TYPE Y AND PRESS THE RETURN KEY"
100 INPUT A$
110 IF A$="Y" THEN GOTO 20
120 GOTO 100
